export function handleDiv() {
    return (
        <div className="new-div">
                <div className="div-inside">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque eros, euismod sed condimentum at, rutrum eu sapien. Maecenas porttitor consequat lacus a placerat. Phasellus tristique tellus nec erat tristique vestibulum. Integer lobortis pellentesque mollis. Quisque nec bibendum turpis, ut rutrum ipsum. Donec blandit sed turpis vel condimentum. Suspendisse sed purus ut urna lacinia ullamcorper. Proin sodales posuere sapien, non ornare lectus tincidunt non. Mauris sit amet elementum ante, quis tempor ex. Mauris sit amet diam enim. Sed accumsan mi posuere accumsan iaculis. Aliquam posuere posuere ipsum, eu commodo nisl viverra at. Pellentesque eget justo sed mi ultrices aliquet scelerisque non lectus. Proin turpis nunc, facilisis nec neque et, congue ullamcorper nisi. Quisque eu tellus sed nunc gravida placerat. Pellentesque accumsan elit in libero bibendum placerat.

Etiam et libero fringilla, euismod mi eget, lobortis lacus. Donec ac mi arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare elit est, id elementum orci ultrices ut. Sed eget risus quam. Duis maximus lacinia metus sit amet suscipit. Nulla imperdiet tempus velit, non rutrum augue tincidunt quis. Nunc malesuada pulvinar nisi vel rhoncus. Quisque vel posuere leo. Fusce consectetur massa sit amet leo eleifend dapibus. Nullam blandit turpis sit amet velit molestie tempor. Ut hendrerit vehicula ligula, et vestibulum enim commodo non.

Aliquam ac diam vitae felis venenatis sollicitudin eget vitae metus. Phasellus mattis pharetra mi vel dictum. Donec blandit sapien neque, ac facilisis eros ornare sit amet. Nam non est vel enim semper sodales non eu urna. Integer maximus enim erat, luctus fringilla quam pellentesque a. Maecenas nec suscipit lorem, non tempor purus. Vestibulum vitae vulputate urna. Morbi aliquet elit in dui feugiat euismod. Mauris lorem ante, bibendum sit amet dictum et, pulvinar vitae risus.

Ut et lacus ante. Donec dictum nibh sed arcu accumsan, ac semper mi eleifend. Phasellus porta mauris augue, sed convallis nunc iaculis sit amet. Suspendisse ultricies leo eget risus egestas, fringilla vulputate odio rutrum. Nullam sagittis tempor commodo. Cras vel posuere sapien. Suspendisse quis dolor elit. Suspendisse at suscipit dolor. Donec vel nisi nibh. Integer in consectetur turpis.

Etiam vel purus venenatis, fermentum metus non, finibus lacus. Pellentesque bibendum suscipit lacus sed egestas. Sed dapibus libero in felis tincidunt, eu iaculis arcu luctus. Mauris felis magna, sagittis ut ornare et, molestie id quam. Fusce sollicitudin metus metus, nec pellentesque neque imperdiet vel. Nam vel sapien nibh. Donec ornare est id nunc dictum facilisis. Nam vestibulum eleifend dui sed finibus. In ultricies lobortis volutpat. Aliquam erat volutpat. Mauris arcu nulla, dapibus at lobortis eget, malesuada ut dui. Donec accumsan viverra nunc eget tristique. Nullam rhoncus mi eget risus sagittis vulputate. Phasellus a feugiat orci. Nunc faucibus in est ut porttitor.

Donec vestibulum sagittis magna, ac lacinia elit placerat sed. Vestibulum velit nisi, blandit eget ipsum scelerisque, ornare sollicitudin quam. Vestibulum eu mi vel augue consectetur porta. Morbi facilisis, nisi non volutpat condimentum, velit arcu dignissim ipsum, id condimentum odio justo nec ipsum. Duis ipsum nunc, pharetra ac interdum vitae, posuere eget erat. Donec mollis ante eleifend massa finibus, eget blandit purus volutpat. Vivamus ac sodales lectus. Donec faucibus quis sapien vel aliquet. Nunc orci lorem, sollicitudin nec ante in, ornare hendrerit lectus. Nulla non finibus turpis. Curabitur a sapien efficitur, ultricies ante et, pretium leo. Integer porta lacus sed elit consectetur dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ut risus nulla.

Nulla sagittis egestas ligula non congue. Mauris sit amet sapien in neque ultrices efficitur. Donec mauris odio, porttitor auctor congue vel, imperdiet ut massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae massa laoreet, pharetra lectus eget, consequat lacus. Praesent pulvinar odio sit amet nibh ultrices, ac volutpat risus venenatis. Maecenas vestibulum nibh dui, id tempor libero sollicitudin sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Praesent et enim eu massa scelerisque porta. Suspendisse potenti. Fusce mauris nisl, sodales a quam non, vehicula bibendum magna. Cras ultrices tellus justo, ut iaculis nisl sollicitudin sit amet. Nam quis convallis arcu, non ullamcorper ex. Aliquam porttitor eget erat in commodo. Morbi mollis ante at augue aliquam suscipit. Proin ex massa, efficitur quis dapibus nec, iaculis eu ipsum. Vivamus varius, dolor et eleifend suscipit, tortor diam convallis ligula, in efficitur diam ligula et est. Praesent molestie turpis non risus pulvinar placerat. Phasellus condimentum mauris erat, a venenatis massa suscipit et. Vestibulum bibendum nibh ullamcorper nibh efficitur vehicula.

Nullam et luctus ante. Integer tincidunt justo eu massa placerat efficitur. In scelerisque aliquam purus non feugiat. Proin sit amet dapibus tortor, at molestie arcu. Vestibulum ipsum eros, posuere vel massa vel, maximus sagittis risus. Nulla pellentesque eros vitae justo malesuada, id dignissim massa ultricies. Curabitur id laoreet libero, eu ultrices lorem. Duis viverra arcu ac metus facilisis laoreet.

Duis eleifend vehicula lacus non tincidunt. Donec id ligula quis felis sodales elementum. Sed fringilla sem eros, at venenatis quam suscipit eu. Curabitur imperdiet turpis vitae velit ullamcorper vulputate. Quisque non erat feugiat, rhoncus justo ac, tristique ante. Sed tellus leo, pellentesque ut leo eget, cursus tincidunt erat. Nam blandit, eros viverra bibendum laoreet, arcu velit aliquet ante, ut feugiat nisi erat in arcu. Integer ornare efficitur purus, et sollicitudin nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut quis ligula dui. In iaculis efficitur nulla, sed pretium nibh tincidunt et. Nullam varius nulla eu porta vehicula. Mauris porta, nulla fermentum pellentesque cursus, nisl odio ornare lacus, ac varius odio erat eget nisi. Praesent sed facilisis ex.  
                </div>
        </div>
    )
}